# Generated by Django 3.0.7 on 2020-06-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(default='', max_length=200)),
                ('dni', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('play_date', models.DateTimeField(auto_now=True, verbose_name='play date')),
            ],
        ),
    ]
