# Generated by Django 3.0.7 on 2020-06-14 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date event'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='event place', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.CharField(default='event topic', max_length=200),
        ),
    ]
