# Generated by Django 3.0.7 on 2020-06-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventinscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventinscription',
            unique_together={('person_name', 'person_email', 'event')},
        ),
    ]
