language: python
python:
  - "3.6.9"

services:
  - postgresql

install:
  - pip install -r requirements.txt

env:
  - ENVIRONMENT=production DJANGO=3.0.7 DB=mysql DATABASE_URL=

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python manage.py test
