# Generated by Django 3.0.7 on 2020-06-20 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Trivia title', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Trivia choice', max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivias.Trivia')),
            ],
        ),
    ]
