# Generated by Django 3.0.7 on 2020-06-18 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='material description', max_length=400)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('content', models.TextField(default='material content', max_length=5000)),
                ('attached_document', models.URLField()),
            ],
        ),
    ]
